name: Conda installation

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Conda installation
    runs-on: windows-2019

    steps:

    - uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: true
        activate-environment: ""

    - name: Create and update environment
      run: |
        create-env.bat
        update-env.bat

    - name: Start JupyterLab
      run: |
        start-jupyterlab.bat
