name: Linting

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Check code quality with pylint and flake8
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Python dependencies including pylint
      run: |
        pip3 install --user -e .[dev,ui]

    - name: Check code quality with pylint
      run: |
        pylint conflowgen

    - name: Check code quality with flake8
      run: |
        flake8
